url: "https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2020-financial-year-provisional/Download-data/annual-enterprise-survey-2020-financial-year-provisional-size-bands-csv.csv"
cache_folder: initial_files
cache: False

output_format: json
output_destination: output_files
rows: 10
cols: 5
